version: "3.9"
services:

  application:
    build: ./application/
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_NAME

  database:
    build: ./database/
    ports:
      - "1433:1433"
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_NAME
      - SA_PASSWORD
      - ACCEPT_EULA
